FROM oven/bun:1 AS builder

WORKDIR /app

COPY frontend/package.json frontend/bun.lockb* ./
RUN bun install

COPY frontend/ .

RUN bun run build

FROM oven/bun:1-alpine

WORKDIR /app

COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json .

EXPOSE 3000

CMD ["bun", "run", "build/index.js"]
