FROM golang:1.26.1-alpine AS builder

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/server
RUN CGO_ENABLED=0 GOOS=linux go build -o /indexer ./cmd/indexer

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /server .
COPY --from=builder /indexer .
COPY backend/internal/migrations ./migrations

EXPOSE 8080

CMD ["./server"]
